### ISSUE TITLE
Cardano.lua:129: attempt to index field 'summary' (a nil value)

### ISSUE THREAD

**Issue by snakelab** [aaronk6/Cardano-MoneyMoney#2]
Hi Folks,
thanks for this extension!
I get this error while trying to get a transaction from Cardano:
Cardano.lua:129: attempt to index field 'summary' (a nil value)

Any idea what is the problem here?

thanks
Hartmut

**Comment by aaronk6** [comment]
Hi, it also stopped working for me. However, I’m seeing a Bad Gateway error instead:

```
1> Sending: POST https://explorer.cardano.org/graphql
1> Der Server Ihrer Bank antwortet mit der Fehlermeldung: »Bad Gateway«  Bitte versuchen Sie es später noch einmal oder wenden Sie sich mit dieser Fehlermeldung an den Support Ihrer Bank.
```

It seems explorer.cardano.org is broken (this is the data source that this extension is relying on). My time is fairly limited right now, so I’ll wait a little more to see if it fixes itself. If it doesn’t, I’ll consider rewriting the extension to use cardanoscan.io, but I can’t give you an ETA. Sorry for no better news!

**Comment by aaronk6** [comment]
Found an answer on Reddit:

> Explorer has been having issues, would assume they will be resolved when the teams come back from the holiday.

I’ll keep an eye on that thread.

([source](https://www.reddit.com/r/cardano/comments/103j2m2/comment/j2zbgbq/?utm_source=share&utm_medium=web2x&context=3))

**Comment by aaronk6** [comment]
2807dbb1a6bac33c2c423ffe79f0779940cfbf0f fixes this by using the [Cardanoscan API](https://cardanoscan.io/api) instead of [Cardano Blockchain Explorer](https://explorer.cardano.org/). Note that I haven’t released a signed version of the extension yet, but I hope to be able to do this soon.
